### ISSUE TITLE
base64url isn't really defined in RFC 4648

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-acme/acme-caa#1]
RFC 7515 defines "Base64url encoding" : https://tools.ietf.org/html/rfc7515#section-2

**Comment by hlandau** [comment]
RFC4648 defines "base64url":

>   This encoding may be referred to as "base64url".  This encoding
>   should not be regarded as the same as the "base64" encoding and
>   should not be referred to as only "base64".  Unless clarified
>   otherwise, "base64" refers to the base 64 in the previous section.
